### ISSUE TITLE
NameError: undefined method `register' for class `RSpec::Core::World'

### ISSUE THREAD

**Issue by bootstraponline** [bootstraponline/sauce_rspec#18]
```
NameError: undefined method `register' for class `RSpec::Core::World'
  gems/sauce_rspec-1.0.7/lib/sauce_rspec/rspec.rb:11:in `alias_method'
  gems/sauce_rspec-1.0.7/lib/sauce_rspec/rspec.rb:11:in `<class:World>'
  gems/sauce_rspec-1.0.7/lib/sauce_rspec/rspec.rb:10:in `<module:Core>'
  gems/sauce_rspec-1.0.7/lib/sauce_rspec/rspec.rb:4:in `<module:RSpec>'
  gems/sauce_rspec-1.0.7/lib/sauce_rspec/rspec.rb:3:in `<top (required)>'
  sauce_connect_ruby/helper/spec_helper.rb:18:in `require'
  sauce_connect_ruby/helper/spec_helper.rb:18:in `<top (required)>'
  sauce_connect_ruby/spec/angular_spec.rb:1:in `require_relative'
  sauce_connect_ruby/spec/angular_spec.rb:1:in `<top (required)>'
  gems/rspec-core-3.5.1/lib/rspec/core/configuration.rb:1435:in `load'
  gems/rspec-core-3.5.1/lib/rspec/core/configuration.rb:1435:in `block in load_spec_files'
  gems/rspec-core-3.5.1/lib/rspec/core/configuration.rb:1433:in `each'
  gems/rspec-core-3.5.1/lib/rspec/core/configuration.rb:1433:in `load_spec_files'
```

**Comment by bootstraponline** [comment]
method is now `record`
https://github.com/rspec/rspec-core/commit/8e564dca9e5962bb6b41865af3fa49f2c3cbe5dd

should probably move to using a public API.

**Comment by bootstraponline** [comment]
https://github.com/bootstraponline/sauce_rspec/commit/3f462f1ca34846b0a9fc42d5f86f99795e0556ca

**Comment by bootstraponline** [comment]
Fixed by https://github.com/bootstraponline/sauce_rspec/commit/f443c4189682243f6a5938aa2146bb5a7949734e
