### ISSUE TITLE
Avoid SSL flakiness of the sauce_ruby gem

### ISSUE THREAD

**Issue by bootstraponline** [bootstraponline/sauce_rspec#9]
```
Errno::ECONNRESET: Connection reset by peer - SSL_connect
/.rvm/gems/ruby-2.2.2/gems/rest-client-1.8.0/lib/restclient/request.rb:413:in `transmit'
/.rvm/gems/ruby-2.2.2/gems/rest-client-1.8.0/lib/restclient/request.rb:176:in `execute'
/.rvm/gems/ruby-2.2.2/gems/rest-client-1.8.0/lib/restclient/request.rb:41:in `execute'
/.rvm/gems/ruby-2.2.2/gems/rest-client-1.8.0/lib/restclient.rb:65:in `get'
/.rvm/gems/ruby-2.2.2/gems/sauce_ruby-3.5.11/lib/sauce/parallel/test_broker.rb:70:in `concurrency'
/.rvm/gems/ruby-2.2.2/gems/sauce_ruby-3.5.11/lib/tasks/parallel_testing.rb:106:in `parse_task_args'
/.rvm/gems/ruby-2.2.2/gems/sauce_ruby-3.5.11/lib/tasks/parallel_testing.rb:79:in `run_parallel_tests'
/.rvm/gems/ruby-2.2.2/gems/sauce_ruby-3.5.11/lib/tasks/parallel_testing.rb:11:in `block (2 levels) in <top (required)>'
```

**Comment by bootstraponline** [comment]
Done. The only Sauce API request is for updating the job status and that's done via Curl with custom retry logic.
